databases:
  - name: agentmarket-db
    databaseName: agentmarket
    plan: free

services:
  - type: web
    name: agentmarket-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run migrate && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agentmarket-db
          property: connectionString
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: STELLAR_SECRET_KEY
        sync: false
      - key: STELLAR_PUBLIC_KEY
        value: GBI7HSC7LUWMMVDAKXK6YHLFZQY3QYOCTNYF4A6EPAHIRD3X5LOBM3HR
      - key: CORS_ORIGIN
        value: "*"
      - key: PLATFORM_STELLAR_WALLET
        value: GBI7HSC7LUWMMVDAKXK6YHLFZQY3QYOCTNYF4A6EPAHIRD3X5LOBM3HR
      - key: STELLAR_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: SOROBAN_CONTRACT_ADDRESS
        value: CBUBTHSZYVAJ6F2X54TWUETKYT5OLD2E6DWEKEOLUBSKFVLNRXRW37VJ
      - key: PINATA_JWT
        sync: false
      - key: PINATA_GATEWAY
        value: https://gateway.pinata.cloud
      - key: COMMISSION_BPS
        value: 2000